package academy.digitallab.store.admin;

import de.codecentric.boot.admin.server.config.EnableAdminServer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

//ESTE  ES UN SERVIDOR CON EL CUAL PODEMOS ADMINISTRAR Y VER INFORMACION RELEVANTE DE CADA UNO DE LOS MICROSERVICIOS
// EN NUESTRO CASO BASTA CON VISITAR: localhost:8089

// FLUJO:
// 1) ESTE SERVIDOR DEBE ESTAR CORRIENDO, CON LA ANOTACION @EnableAdminServer
// 2) CADA MICROSERVICIO, AL LEVANTARSE, SE CONECTA  A ESTE SERVIDOR, A TRAVES DE SU BOOTSTRAP.YML, TAL Y COMO LO HACEN CON EL SERVIDOR CENTRALIZADO.
// BASTA CON QUE CADA MICROSERVICIO TENGA LA DEPENDENCIA spring-boot-admin-starter-client
// 3) ESTE SERVIDOR LOCALIZA LA UBICACION DE CADA MICROSERVICIO A TRAVÉS DEL SERVIDOR EUREKA, MEDIANTE EL APPLICATION.PROPERTIES
// 4)  ESTE SERVIDOR LOCALIZA LA INFORMACIÓN A MOSTRAR A TRAVÈS DE ACTUATOR. PUEDES USAR ACTUATOR SIN USAR EL SERVIDOR ADMIN, MEDIANTE EL NAVEGADOR:
// localhost:8094/actuator .PARA USAR ACTUATOR BASTA CON USAR EN CADA MICROSERVICIO LA DEPENDENCIA spring-boot-starter-actuator
// Y COLOCAR UNA CONFIGURACION EN EL  ARCHIVO DE PROPIEDADES QUE SE ENCUENTRA EN LA NUBE DE CADA MICROSERVICIO.
@SpringBootApplication
@EnableAdminServer
public class AdminServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(AdminServiceApplication.class, args);
	}

}
